create structure, some endpoints and models, def token system
keyzoz/user-management pull request #1
Opened 2023-09-08 09:49 UTC by keyzoz

i will change token system and add aws in the future

2023-09-11 11:34 UTC, sabbra-cadabra requested changes
Something seems off about your project structure. Did you do it by yourself or used another repository as an example?

2023-09-11 11:34 UTC, sabbra-cadabra commented on setup.cfg
why do you need setup.cfg?

2023-09-11 11:34 UTC, sabbra-cadabra commented on docker-compose-local.yaml
> +      - POSTGRES_DB=postgres
you may want to use .env file for your variables

2023-09-11 11:34 UTC, sabbra-cadabra commented on docker-compose-local.yaml
> +    container_name: "db"
if you explicitly give a name for your container it makes sense to pass another name. it you want it to be called the same this option is redundant

2023-09-11 11:34 UTC, sabbra-cadabra commented on docker-compose-local.yaml
I can't find FastAPI app in this file. Please add to run all your services together

2023-09-11 11:34 UTC, sabbra-cadabra commented on Makefile
> +export DOCKER_DEFAULT_PLATFORM=linux/arm64/v8
do you have any requirements for a specific platform?

2023-09-11 11:34 UTC, sabbra-cadabra commented on requirements.txt
Let's use pipenv or poetry for managing dependencies.

2023-09-11 11:34 UTC, sabbra-cadabra commented on settings.py
> +    default="postgresql+asyncpg://postgres:postgres@0.0.0.0:5444/postgres",
please do not hardcode any database settings! you must use .env.

2023-09-11 11:34 UTC, sabbra-cadabra commented on src/api/actions/user.py
> +async def _create_new_user(body: UserCreate, session) -> ShowUser:
I have a strong feeling you must employ Class based CRUD. Also think of Ports and Adapters pattern from the requirements.

2023-09-11 11:34 UTC, sabbra-cadabra commented on src/api/routers/user_router.py
> +from src.api.actions.user import (_create_new_user, _delete_user,
instead of using them as single functions please use a UserCRUD class.

2023-09-11 11:56 UTC, keyzoz commented on setup.cfg
if i will need some setups for my pre-commits

2023-09-14 12:21 UTC, sabbra-cadabra approved these changes

2023-09-14 12:21 UTC, sabbra-cadabra commented on src/api/routers/user_router.py
> +    try:
you can put full block in one try ... except

2023-09-20 11:24 UTC, closed without merging