Feature/aws services
keyzoz/user-management pull request #4
Opened 2023-09-13 18:04 UTC by keyzoz

added redis in endpoints

2023-09-14 08:53 UTC, keyzoz commented
added query endpoint

2023-09-14 12:46 UTC, sabbra-cadabra requested changes
Nice work! Please pay attention to comments.
Also I'd recommend you to explore some of the naming best practices.

2023-09-14 12:46 UTC, sabbra-cadabra commented on src/api/actions/token.py
> +def store_reset_token(redis, email, token):
Make a class for communication with Redis.

2023-09-14 12:46 UTC, sabbra-cadabra commented on src/api/actions/token.py
> +def store_reset_token(redis, email, token):
And ResetTokenService with self.storage = RedisStorage (this will contain methods that put and retrieve data from redis).

2023-09-14 12:46 UTC, sabbra-cadabra commented on src/api/routers/login_router.py
> +            reset_token = generate_reset_password_token()
if you make a class user for Token managing you'll be able to call only one of its method here and improve code structure

2023-09-14 12:46 UTC, sabbra-cadabra commented on src/api/routers/login_router.py
> +            return {"message": "error"}
you don't want to actually raise an Error and have an fastapi ExceptionHandler?

2023-09-14 12:46 UTC, sabbra-cadabra commented on src/db/redis_db.py
And this is the client you may pass to RedisStorage as a class property.

2023-09-14 12:50 UTC, keyzoz commented on src/api/routers/login_router.py
> +            return {"message": "error"}
oh, i'm sorry, just missed it, didn't remove the stoppers. ofc, will change it

2023-09-20 10:43 UTC, sabbra-cadabra approved these changes

2023-09-20 10:43 UTC, sabbra-cadabra commented on src/api/routers/user_router.py
> +    aws_session = aioboto3.Session()
a lot of logic in this view. You can have a separate class to handle s3 operations. Like S3Storage or StorageService etc

2023-10-10 10:53 UTC, merged